# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-16 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0004_auto_20170716_0828'),
        ('questions', '0002_question_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='screenshots',
            field=models.ManyToManyField(related_name='questions', to='screenshots.Screenshot'),
        ),
    ]
