# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-23 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20170723_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ('accepted', 'created'), 'permissions': (('view_response', 'View response'),)},
        ),
    ]
