# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161220_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='features_following',
            field=models.ManyToManyField(null=True, related_name='followers', to='products.Feature'),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
