# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-16 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='file_path',
        ),
        migrations.AddField(
            model_name='screenshot',
            name='image',
            field=models.FileField(default='napa.jpg', upload_to='screenshots/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
