# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-16 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0002_auto_20170716_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='products.Feature'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='questions.Question'),
        ),
    ]
