# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-16 08:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('screenshots', '0003_auto_20170716_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='screenshot',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='screenshot',
            name='question',
        ),
        migrations.AddField(
            model_name='screenshot',
            name='admins',
            field=models.ManyToManyField(related_name='screenshots_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
