# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-05 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        ('accounts', '0003_auto_20170217_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='primary_account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='primary_account', to='orgs.Org'),
            preserve_default=False,
        ),
    ]
