# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-05 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_primary_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='primary_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Org'),
        ),
    ]
