# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-05 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170705_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='primary_account',
            new_name='primary_org',
        ),
    ]
