# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-05 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170705_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='primary_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.Org'),
        ),
    ]
