# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-15 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170705_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_pic',
            field=models.FileField(default='pic', upload_to='profile_pics/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='primary_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_accounts', to='orgs.Org'),
        ),
    ]
