# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-02 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20171230_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
