# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-04 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180104_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cc_last_four',
            field=models.IntegerField(null=True),
        ),
    ]
