# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-04 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180104_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cc_active',
            field=models.BooleanField(default=False),
        ),
    ]
