# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-05 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180104_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='features_following',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to='products.Feature'),
        ),
    ]
