# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-16 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenshots', '0004_auto_20170716_0828'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='screenshots',
            field=models.ManyToManyField(related_name='screenshots', to='screenshots.Screenshot'),
        ),
    ]
