# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-17 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170716_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='fake'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default='fake', upload_to='product_pics/'),
            preserve_default=False,
        ),
    ]
