# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-22 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170717_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('title',), 'permissions': (('view_prod', 'View prod'),)},
        ),
    ]
