# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-23 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20170722_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ('title',), 'permissions': (('view_feat', 'View feature'), ('create_response', 'Create Question Response'))},
        ),
    ]
