# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-25 18:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20170723_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='engagement_lists',
            field=models.ManyToManyField(blank=True, related_name='features', to='feature_lists.EngagementList'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='experts',
            field=models.ManyToManyField(blank=True, related_name='expert_features', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feature',
            name='screenshots',
            field=models.ManyToManyField(blank=True, related_name='features', to='screenshots.Screenshot'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='features', to='orgs.Skill'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='top_lists',
            field=models.ManyToManyField(blank=True, related_name='features', to='feature_lists.TopList'),
        ),
    ]
