# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='email_all',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='org',
            name='email_domain',
            field=models.CharField(default='coreygarvey.com', max_length=50),
            preserve_default=False,
        ),
    ]
