# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-11 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=50)),
                ('public', models.BooleanField(default=True)),
                ('client', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('admins', models.ManyToManyField(related_name='elists_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('title',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=50)),
                ('public', models.BooleanField(default=True)),
                ('admins', models.ManyToManyField(related_name='tlists_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('title',),
                'abstract': False,
            },
        ),
    ]
