# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-20 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='org',
            options={'ordering': ('title',), 'permissions': (('can_view_org', 'Can view org'),)},
        ),
    ]
