# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-22 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_auto_20170722_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='org',
            options={'ordering': ('title',), 'permissions': (('view_org', 'View org'), ('create_prod', 'Create org product'), ('create_feat', 'Create org feature'), ('create_anno', 'Create org annotation'), ('create_quest', 'Create org question'))},
        ),
    ]
