# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-02 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_auto_20170722_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='subscription_id',
            field=models.CharField(default='monthly', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='org',
            name='subscription_type',
            field=models.CharField(default='abc', max_length=30),
            preserve_default=False,
        ),
    ]
