# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-04 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_org_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='sub_status',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
