# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-04 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_auto_20180104_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='org',
            old_name='sub_status',
            new_name='sub_status_int',
        ),
    ]
