# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-04 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0010_auto_20180104_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='sub_status_int',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
