# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-04 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0011_auto_20180104_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='current_period_end',
            field=models.IntegerField(blank=True, default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='org',
            name='current_period_start',
            field=models.IntegerField(blank=True, default=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='org',
            name='subscription_amount',
            field=models.IntegerField(blank=True, default=12),
            preserve_default=False,
        ),
    ]
