# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-04 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0012_auto_20180104_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='subscription_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
