# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-04 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0014_auto_20180104_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='current_period_end',
        ),
        migrations.RemoveField(
            model_name='org',
            name='current_period_start',
        ),
    ]
