# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-05 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0016_auto_20180104_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='unpaid_invoice',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
