# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 23:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feature_lists', '0001_initial'),
        ('orgs', '0002_auto_20161220_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('admins', models.ManyToManyField(related_name='features_admin', to=settings.AUTH_USER_MODEL)),
                ('engagement_lists', models.ManyToManyField(related_name='features', to='feature_lists.EngagementList')),
                ('experts', models.ManyToManyField(related_name='expert_features', to='orgs.Expert')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_admin', to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='products.Feature')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('admins', models.ManyToManyField(related_name='products_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='feature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.Product'),
        ),
        migrations.AddField(
            model_name='feature',
            name='skills',
            field=models.ManyToManyField(related_name='features', to='orgs.Skill'),
        ),
        migrations.AddField(
            model_name='feature',
            name='top_lists',
            field=models.ManyToManyField(related_name='features', to='feature_lists.TopList'),
        ),
    ]
